### ISSUE TITLE
 Possibility of use as an underwater sonar?

### ISSUE THREAD

**Issue by Yarulik** [kelu124/echomods#11]
Hello dear developers!
Thank you for such a beautiful and interesting project!

I want to build an open source underwater sonar project, but there is very little information about such things, your project has revealed a lot to me in terms of component base.

My question is: is it possible to use it for underwater scanning, if? And underwater measuring the quality of the metal surface?

Perhaps you will give me a more detailed answer!

I have an underwater vehicle (ROV) and I want to make a near-field scanner with rotating PZT

**Comment by kelu124** [comment]
Hi @Yarulik , good to read from you, and thanks for your kind words.
I assume it'd be possible to test this, what's the distance range you'd like to measure as of sonar activities?
Moreover, depends on what you'd like to image underwater, but I guess this could work as well.. depending on your constraints.
What is your precise objective? Getting the thickness of a piece of metal? Getting an idea of the surface of the piece of metal?
Any clarification would be precious =)

**Comment by Yarulik** [comment]
1. I want to make a simple echo sounder at a high frequency (1.7-2 MHz) to reflect from the bottom, as minimal as possible, for autopilot on ROV (the depth sensor is already standing)
2. I want to make an affordable sonar, possibly with a moving part, similar to the Tritech Gemini, for orientation and visualization under water at short distances.
3. There is a need to measure the thickness of the metal (surface condition) of piles, pipes of bridges, ships.
This direction is new for me, I have to learn from scratch, this is my home hobby and is not related to work. Therefore, I can not afford to buy finished products like Tritech. But I can create and do complex projects, I like it)
I also want to make these projects open, this will allow schoolchildren, students, and self-taught people like me to be able to study the world around and water spaces.

the first two projects are priority for me, they will help me study and identify shortcomings, as well as reduce the budget at the design stage. I ordered many core components from your projects. In the new year I will do.

@ kelu124 Happy New Year to you !!!! Health! Joy! Good luck to you and your family!

**Comment by kelu124** [comment]
Closing the issue as it is ongoing work on your side, looking forward to your results !
