### ISSUE TITLE
could not insert module ./adc.ko: Invalid module format

### ISSUE THREAD

**Issue by Arash68** [kelu124/echomods#6]
Hi,

I got your image and then use ./run.sh to get the driver, and I got the error "could not insert module ./adc.ko: Invalid module format". When I try "cat /dev/hsdk > myfilename.dat" I don't see any data in the file and myfilename.dat is empty.

Would you please help, how I can fix this problem?
Moreover, Can I get the instruction of how to just use ADC on a fresh Raspbian, please?

Best Regards,
Arash

**Comment by kelu124** [comment]
Hey Arah,
Sure thing. So it seems the module doesn't work on recent RPi3 distros (the image works on a RPi W flawlessly).
So the driver needs to be recompiled, and we have some issues ongoing:
https://stackoverflow.com/questions/51160704/difficult-incompatible-pointer-type-warning

@eiffel-fl : any pro tips there? ;)

Cheers

**Comment by kelu124** [comment]
Closing it as old - seemingly closed =)
