### ISSUE TITLE
How can we use this module for Raspberry pi 3

### ISSUE THREAD

**Issue by naventenxer** [kelu124/echomods#8]
I Tried this module with pi zero, it absolutely works fine, now i want to use this module with raspberry pi 3.
It shows the Error like this
make: *** [all] Error 2
rmmod: ERROR: Module adc is not currently loaded
insmod: ERROR: could not insert module ./adc.ko: Invalid module format

**Comment by kelu124** [comment]
hi @naventenxer - thanks for the shout.
You will have seen for example the code for the kernel for RPi3, refering this file: https://github.com/kelu124/echomods/blob/4f865ea06417451a51e59ce5611919fa0a85e822/elmo/standard_driver_RPi3.c 
You can refer to comment on line 47: actually __BCM2708_PERI_BASE__ changes from RPi 0/W to RPi3.
More details for example on : https://www.raspberrypi.org/forums/viewtopic.php?t=142439

**Comment by kelu124** [comment]
Deemed closed =)
